Repository AvianNetwork/Avian, pull requests merged in 2022-09, with the labels that each got.

#160 ci: Use ubuntu-20.04 image
  .github/workflows/c-cpp.yml
Labels: test

#161 [URGENT] consensus: Enforce asset coinbase checks and enforced values.
  src/assets/assets.cpp
  src/consensus/consensus.h
  src/validation.cpp
  src/validation.h
Labels: urgent, consensus

#115 qt: Add wallet repair tab
  src/qt/avian.cpp
  src/qt/aviangui.cpp
  src/qt/aviangui.h
  src/qt/forms/debugwindow.ui
  src/qt/rpcconsole.cpp
  src/qt/rpcconsole.h
Labels: enhancement, ui

#165 backport: Fix bug with in memory qualifier address checking
  src/assets/assets.cpp
Labels: bug, backport

#158 trivial: Rename ambiguous UAHFs (FORKID and unused assets)
  src/consensus/consensus.h
  src/rpc/rawtransaction.cpp
  src/script/sign.cpp
  src/validation.cpp
  src/validation.h
  src/wallet/wallet.cpp
Labels: consensus, cleanup

#170 chain: Use correct BIP44 cointype for mainnet (921)
  src/chainparams.cpp
Labels: cleanup, test

#171 Print CreateNewBlock() when BENCH debug is set
  src/miner.cpp
Labels: cleanup

#157 validation: Do not check PoW when downloading headers during IBD
  src/validation.cpp
Labels: enhancement

#164 qt: 4.1 UI fixup
  src/qt/forms/overviewpage.ui
  src/qt/guiconstants.h
  src/qt/overviewpage.cpp
  src/qt/platformstyle.cpp
  src/qt/res/css/Dark.css
  src/qt/res/css/Light.css
Labels: ui

#172 qt: Check wallet model to prevent segfault
  src/qt/overviewpage.cpp
Labels: bug

#162 ans: Implement Avian Name System (AIP-4)
  src/Makefile.am
  src/assets/ans.cpp
  src/assets/ans.h
  src/assets/assetdb.cpp
  src/assets/assetdb.h
  src/assets/assets.cpp
  src/assets/assets.h
  src/assets/assettypes.h
  src/chainparams.cpp
  src/coins.cpp
  src/consensus/consensus.h
  src/consensus/params.h
  src/core_write.cpp
  src/flightplans/avianlib.cpp
  src/qt/assetrecord.h
  src/qt/assettablemodel.cpp
  src/qt/assettablemodel.h
  src/qt/createassetdialog.cpp
  src/qt/createassetdialog.h
  src/qt/forms/createassetdialog.ui
  src/qt/forms/reissueassetdialog.ui
  src/qt/overviewpage.cpp
  src/qt/overviewpage.h
  src/qt/reissueassetdialog.cpp
  src/qt/reissueassetdialog.h
  src/qt/sendassetsentry.cpp
  src/rpc/assets.cpp
  src/rpc/rawtransaction.cpp
  src/rpc/server.cpp
  src/test/assets/asset_reissue_tests.cpp
  src/test/assets/asset_tests.cpp
  src/test/assets/asset_tx_tests.cpp
  src/test/assets/serialization_tests.cpp
  src/validation.cpp
  src/validation.h
Labels: enhancement, ui, consensus, test

#173 trival: Remove "backup" nodes
  src/chainparams.cpp
Labels: cleanup

#159 Corrected Grammatical errors
  README.md
Labels: documentation

#175 Update DNS seeders and fixed seeds
  contrib/seeds/makeseeds.py
  contrib/seeds/nodes_main.txt
  src/chainparams.cpp
  src/chainparamsseeds.h
Labels: cleanup

#177 docs: Update man pages
  contrib/devtools/gen-manpages.sh
  doc/man/avian-cli.1
  doc/man/avian-qt.1
  doc/man/aviand.1
Labels: documentation

#168 block: Cache PoW hashs
  .github/workflows/c-cpp.yml
  src/Makefile.am
  src/algo/hash_algos.h
  src/flat-database.h
  src/init.cpp
  src/miner.cpp
  src/pow.cpp
  src/pow.h
  src/primitives/block.cpp
  src/primitives/block.h
  src/primitives/powcache.cpp
  src/primitives/powcache.h
  src/serialize.h
  src/span.h
  src/uint256.cpp
  src/uint256.h
  src/unordered_lru_cache.h
  src/util.h
  src/validation.cpp
Labels: enhancement, test

#176 docs: Add release notes for 4.1
  doc/release-notes/release-notes-4.1.0.md
Labels: documentation

#87 5% block reward code to AVN foundation wallet
  src/Makefile.am
  src/bench/checkblock.cpp
  src/blockencodings.cpp
  src/chainparams.cpp
  src/consensus/params.h
  src/consensus/tx_verify.cpp
  src/consensus/tx_verify.h
  src/founder_payment.cpp
  src/founder_payment.h
  src/miner.cpp
  src/primitives/block.h
  src/rpc/mining.cpp
  src/test/assets/asset_tx_tests.cpp
  src/test/sighash_tests.cpp
  src/test/transaction_tests.cpp
  src/txmempool.cpp
  src/validation.cpp
  src/validation.h
  src/version.h
  src/wallet/walletdb.cpp
Labels: enhancement, consensus
